image: jypark0209/plc-build:latest
#image: ubuntu:20.04 테스트용 이미지

before_script:
  - echo "This is OTACauth for PLC build container."
  


stages:
  - build
  - test


.build_job_template:
  script:
    - export PATH=$PATH:/home/plcncli
    - mkdir -p $CI_PROJECT_DIR/artifacts
    - echo "----------${TARGET} .so file build start----------"
    - cd /home/otacauthServer/${TARGET_LOW}/work
    - plcncli new project -n OTACauth
    - cd OTACauth
    - rm -rf src/*
    - cp -r $CI_PROJECT_DIR/* .
    - plcncli set target --add -n ${TARGET}
    - plcncli build
    - cd /home/otacauthServer/${TARGET_LOW}/work/OTACauth/bin/${TARGET}_23.0.${VERSION}/Release/lib
    - mv libOTACauth.so libOTACauth-${TARGET_LOW}.so
    - cp libOTACauth-${TARGET_LOW}.so $CI_PROJECT_DIR/artifacts/
  artifacts:
    expire_in: 1 day
    paths:
    - artifacts/

build-epc1502:
  extends: .build_job_template
  stage: build
  variables:
    TARGET: EPC1502
    VERSION: 6.62
    TARGET_LOW: epc1502

build-epc1522:
  extends: .build_job_template
  stage: build
  variables:
    TARGET: EPC1522
    VERSION: 6.54
    TARGET_LOW: epc1522

build-axcf3152:
  extends: .build_job_template
  stage: build
  variables:
    TARGET: AXCF3152
    VERSION: 2.56
    TARGET_LOW: axcf3152

# check_build:
  # stage: test
  # script:
    # - ls -al artifacts/

variables:
  SAST_DISABLED: "false"

include:
  - template: Security/SAST.gitlab-ci.yml #코드 취약점 점검
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml #sbom 생성 (lock파일 필요)


# sast:
#   stage: security
#   allow_failure: true

# override the dependency scanning job
# gemnasium-dependency_scanning:
#   tags: [ saas-linux-large-amd64 ]
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main"
#     - if: $CI_MERGE_REQUEST_IID



export-merged-sbom:
  before_script:
    - apt-get update
    - apt-get install -y  jq curl dos2unix
    - echo "$PRIVATE_TOKEN"
  stage: .post
  script:
    - |
      curl --header "Authorization: Bearer $PRIVATE_TOKEN" --output export.sh --url "https://gitlab.com/api/v4/snippets/3730445/raw"
    - dos2unix export.sh
    - bash export.sh
  artifacts:
    paths:
      - "gl-sbom-merged-*.cdx.json"



